@extends('layouts.superadmin')

@section('title', 'CashPilot — Payments')

@section('content')
<section id="sec-all-payments">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">All Payments</h1>
            <p class="text-[13.2px] text-inksoft">Every transaction processed on CashPilot.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>Export</button>
        </div>
    </div>
    <div class="mb-6 grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-4">
        <div class="rounded-[10px] border border-line bg-panel p-[18px] dark:border-[#2a2c3d] dark:bg-[#1b1d2a]"><div class="mb-[3px] text-[23px] font-bold tracking-tight">$68,240</div><div class="text-[12.6px] text-inksoft">This month</div></div>
        <div class="rounded-[10px] border border-line bg-panel p-[18px] dark:border-[#2a2c3d] dark:bg-[#1b1d2a]"><div class="mb-[3px] text-[23px] font-bold tracking-tight">$812,940</div><div class="text-[12.6px] text-inksoft">All time</div></div>
        <div class="rounded-[10px] border border-line bg-panel p-[18px] dark:border-[#2a2c3d] dark:bg-[#1b1d2a]"><div class="mb-[3px] text-[23px] font-bold tracking-tight">98.4%</div><div class="text-[12.6px] text-inksoft">Success rate</div></div>
        <div class="rounded-[10px] border border-line bg-panel p-[18px] dark:border-[#2a2c3d] dark:bg-[#1b1d2a]"><div class="mb-[3px] text-[23px] font-bold tracking-tight">$1,140</div><div class="text-[12.6px] text-inksoft">Failed this month</div></div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex flex-wrap items-center gap-2.5 border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div class="flex min-w-[200px] items-center gap-2 rounded-lg border border-line bg-bg px-3 py-2 text-[12.8px] text-[#9497ab] dark:border-[#2a2c3d] dark:bg-[#12131c] dark:text-[#8d90ac] [&>svg]:size-[14px] [&>svg]:flex-none"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input placeholder="Search transaction ID or user" class="w-full bg-transparent text-[12.8px] text-ink outline-none dark:text-[#ededf5]"></div>
            <button type="button" class="rounded-lg border border-line bg-panel px-3 py-2 text-[12.6px] text-[#565a73] dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#c7c9de]">Method: All ▾</button>
            <button type="button" class="rounded-lg border border-line bg-panel px-3 py-2 text-[12.6px] text-[#565a73] dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#c7c9de]">Status: All ▾</button>
            <button type="button" class="rounded-lg border border-line bg-panel px-3 py-2 text-[12.6px] text-[#565a73] dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#c7c9de]">Date range ▾</button>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Transaction ID</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">User</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Plan</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Amount</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Method</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Date</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">TXN-93021</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Mahin Rahman</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Pro</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$12.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Visa •••• 4021</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">3 Sep 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Success</span></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">TXN-93020</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Farzana Akter</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Business</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$29.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">bKash</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">3 Sep 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Success</span></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">TXN-93019</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Kabir Hossain</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Pro</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$12.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Mastercard •••• 7742</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">3 Sep 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-badtint px-2.5 py-1 text-[11.6px] font-bold text-bad dark:bg-[#3a1613] dark:text-[#f2685c]">Failed</span></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">TXN-93018</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Nusrat Sultana</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Pro</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$12.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Visa •••• 1187</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">2 Sep 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Success</span></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">TXN-93017</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Tanvir Islam</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Business</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$29.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Nagad</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">2 Sep 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-warntint px-2.5 py-1 text-[11.6px] font-bold text-warn dark:bg-[#3a2f10] dark:text-[#e8be55]">Pending</span></td></tr>
                </tbody>
            </table>
        </div>
        <div class="flex items-center justify-between px-5 py-3.5 text-[12.3px] text-inksoft">
            <span>Showing 1–5 of 62,410 transactions</span>
            <div class="flex gap-1.5"><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">‹</button><button type="button" class="size-7 rounded-[7px] border border-brand bg-brand text-xs font-bold text-white dark:border-[#e0655e] dark:bg-[#e0655e]">1</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">2</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">3</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">›</button></div>
        </div>
    </div>
</section>

<section id="sec-refunds">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Refunds</h1>
            <p class="text-[13.2px] text-inksoft">Refund requests and their processing status.</p>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex flex-wrap items-center gap-2.5 border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div class="flex min-w-[200px] items-center gap-2 rounded-lg border border-line bg-bg px-3 py-2 text-[12.8px] text-[#9497ab] dark:border-[#2a2c3d] dark:bg-[#12131c] dark:text-[#8d90ac] [&>svg]:size-[14px] [&>svg]:flex-none"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><input placeholder="Search refund ID or user" class="w-full bg-transparent text-[12.8px] text-ink outline-none dark:text-[#ededf5]"></div>
            <button type="button" class="rounded-lg border border-line bg-panel px-3 py-2 text-[12.6px] text-[#565a73] dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#c7c9de]">Status: All ▾</button>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Refund ID</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">User</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Original TXN</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Amount</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Reason</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Requested</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]"></th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">RF-2210</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Farzana Akter</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">TXN-91832</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$29.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Accidental purchase</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">2 Sep 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-warntint px-2.5 py-1 text-[11.6px] font-bold text-warn dark:bg-[#3a2f10] dark:text-[#e8be55]">Pending</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" title="Approve" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"/></svg></button><button type="button" title="Reject" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">RF-2209</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Rezaul Karim</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">TXN-91406</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$12.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Didn&#39;t use the service</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">29 Aug 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Approved</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">RF-2208</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Priya Sharma</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">TXN-90998</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$29.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Charged twice</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">24 Aug 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Approved</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">RF-2207</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Kabir Hossain</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">TXN-90711</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$12.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">Not satisfied with service</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">18 Aug 2026</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-badtint px-2.5 py-1 text-[11.6px] font-bold text-bad dark:bg-[#3a1613] dark:text-[#f2685c]">Rejected</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg></button></div></td></tr>
                </tbody>
            </table>
        </div>
        <div class="flex items-center justify-between px-5 py-3.5 text-[12.3px] text-inksoft">
            <span>Showing 1–4 of 96 refund requests</span>
            <div class="flex gap-1.5"><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">‹</button><button type="button" class="size-7 rounded-[7px] border border-brand bg-brand text-xs font-bold text-white dark:border-[#e0655e] dark:bg-[#e0655e]">1</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">2</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">›</button></div>
        </div>
    </div>
</section>
@endsection
