@extends('layouts.superadmin')

@section('title', 'CashPilot — Settings')

@section('content')
<section id="sec-general-settings">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">General Settings</h1>
            <p class="text-[13.2px] text-inksoft">Core configuration for the CashPilot platform.</p>
        </div>
    </div>
    <div class="mb-[18px] flex w-fit gap-1 rounded-[9px] border border-line bg-bg p-1 dark:border-[#2a2c3d] dark:bg-[#12131c]">
        <button type="button" data-tab-btn data-active="true" class="cursor-pointer rounded-[7px] px-4 py-2 text-[12.8px] font-semibold text-inksoft data-[active=true]:bg-panel data-[active=true]:text-ink data-[active=true]:shadow dark:data-[active=true]:bg-[#1b1d2a] dark:data-[active=true]:text-[#ededf5]">General</button>
        <button type="button" data-tab-btn data-active="false" class="cursor-pointer rounded-[7px] px-4 py-2 text-[12.8px] font-semibold text-inksoft data-[active=true]:bg-panel data-[active=true]:text-ink data-[active=true]:shadow dark:data-[active=true]:bg-[#1b1d2a] dark:data-[active=true]:text-[#ededf5]">Notification</button>
        <button type="button" data-tab-btn data-active="false" class="cursor-pointer rounded-[7px] px-4 py-2 text-[12.8px] font-semibold text-inksoft data-[active=true]:bg-panel data-[active=true]:text-ink data-[active=true]:shadow dark:data-[active=true]:bg-[#1b1d2a] dark:data-[active=true]:text-[#ededf5]">Languages</button>
        <button type="button" data-tab-btn data-active="false" class="cursor-pointer rounded-[7px] px-4 py-2 text-[12.8px] font-semibold text-inksoft data-[active=true]:bg-panel data-[active=true]:text-ink data-[active=true]:shadow dark:data-[active=true]:bg-[#1b1d2a] dark:data-[active=true]:text-[#ededf5]">Currencies</button>
        <button type="button" data-tab-btn data-active="false" class="cursor-pointer rounded-[7px] px-4 py-2 text-[12.8px] font-semibold text-inksoft data-[active=true]:bg-panel data-[active=true]:text-ink data-[active=true]:shadow dark:data-[active=true]:bg-[#1b1d2a] dark:data-[active=true]:text-[#ededf5]">Privacy policy</button>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div><h3 class="text-[14.5px] font-semibold">App information</h3><div class="mt-0.5 text-xs text-inksoft">Shown across the app and support emails</div></div>
        </div>
        <div class="grid grid-cols-1 gap-4 p-5 lg:grid-cols-2">
            <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">App name</label><input type="text" value="CashPilot" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Support email</label><input type="email" value="support@cashpilot.app" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Default timezone</label><select class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"><option>GMT+6 — Dhaka</option><option>GMT+0 — London</option><option>GMT-5 — New York</option></select></div>
            <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Default date format</label><select class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"><option>DD MMM YYYY</option><option>MM/DD/YYYY</option><option>YYYY-MM-DD</option></select></div>
            <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">App description <span class="text-[11.3px] font-normal text-inksoft">(shown on the Play Store / App Store listing)</span></label><textarea class="min-h-[90px] w-full resize-y rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]">CashPilot helps you track income and expenses, manage budgets, and take control of your money — all in one simple app.</textarea></div>
        </div>
        <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#e0655e] dark:bg-[#e0655e] dark:hover:bg-[#f09690]">Save changes</button>
        </div>
    </div>

    <div class="mt-6 rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div><h3 class="text-[14.5px] font-semibold">Maintenance mode</h3><div class="mt-0.5 text-xs text-inksoft">Temporarily disable access for all non-admin users</div></div>
        </div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Enable maintenance mode</div><div class="mt-0.5 text-xs text-inksoft">Users will see a &#34;we&#39;ll be back soon&#34; screen</div></div><button type="button" data-switch data-on="false" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Allow new signups</div><div class="mt-0.5 text-xs text-inksoft">Turn off to temporarily pause new registrations</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
    </div>
</section>

<section id="sec-settings-notification">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Notification Settings</h1>
            <p class="text-[13.2px] text-inksoft">Control which system notifications are sent automatically.</p>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Payment failed alerts</div><div class="mt-0.5 text-xs text-inksoft">Notify users automatically when a charge fails</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Subscription renewal reminders</div><div class="mt-0.5 text-xs text-inksoft">Send a reminder 3 days before renewal</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Monthly report</div><div class="mt-0.5 text-xs text-inksoft">Send a spending summary on the 1st of each month</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">New feature announcements</div><div class="mt-0.5 text-xs text-inksoft">Notify users when new features ship</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Admin email alerts</div><div class="mt-0.5 text-xs text-inksoft">Email the super admin for high-priority support tickets</div></div><button type="button" data-switch data-on="false" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Suspicious login alerts</div><div class="mt-0.5 text-xs text-inksoft">Notify staff when a login is blocked as suspicious</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
    </div>
</section>

<section id="sec-languages">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Languages</h1>
            <p class="text-[13.2px] text-inksoft">Languages available to CashPilot users.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#e0655e] dark:bg-[#e0655e] dark:hover:bg-[#f09690] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Add language</button>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Language</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Code</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Translation coverage</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Default</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]"></th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">English</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">en</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">100%</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">✅</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Bengali</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">bn</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">96%</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Hindi</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">hi</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">82%</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Arabic</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">ar</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">58%</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-warntint px-2.5 py-1 text-[11.6px] font-bold text-warn dark:bg-[#3a2f10] dark:text-[#e8be55]">In progress</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><button type="button" data-switch data-on="false" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Indonesian</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">id</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">21%</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-muted px-2.5 py-1 text-[11.6px] font-bold text-[#6b7089] dark:bg-[#242639] dark:text-[#b3b6cc]">Draft</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><button type="button" data-switch data-on="false" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#e0655e]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

<section id="sec-currencies">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Currencies</h1>
            <p class="text-[13.2px] text-inksoft">Currencies supported for pricing and transactions.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#e0655e] dark:bg-[#e0655e] dark:hover:bg-[#f09690] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Add currency</button>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Currency</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Code</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Symbol</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Exchange rate (to USD)</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Default</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]"></th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">US Dollar</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">USD</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">$</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">1.00</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">✅</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Bangladeshi Taka</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">BDT</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">৳</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">121.40</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Indian Rupee</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">INR</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">₹</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">87.10</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Euro</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">EUR</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">€</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">0.92</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Active</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">UAE Dirham</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">AED</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">د.إ</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">3.67</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">—</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-muted px-2.5 py-1 text-[11.6px] font-bold text-[#6b7089] dark:bg-[#242639] dark:text-[#b3b6cc]">Inactive</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button></div></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

<section id="sec-privacy-policy">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Privacy Policy</h1>
            <p class="text-[13.2px] text-inksoft">Edit the legal text shown to users in the app and on the website.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>Preview</button>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div><h3 class="text-[14.5px] font-semibold">Policy content</h3><div class="mt-0.5 text-xs text-inksoft">Last updated 14 Jul 2026 by Sarah Ahmed</div></div>
        </div>
        <div class="p-5">
            <textarea class="min-h-[260px] w-full resize-y rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]">CashPilot Privacy Policy

1. Information we collect
We collect the account information you provide (name, email) and the financial data you choose to enter, such as income, expenses, and account balances.

2. How we use your information
Your data is used to power your dashboards, reports, and budgets, and is never sold to third parties.

3. Data storage &amp; security
All data is encrypted in transit and at rest. You may request full account deletion at any time from Settings.

4. Your rights
You may access, export, or delete your data at any time by contacting support@cashpilot.app.</textarea>
        </div>
        <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#e0655e] dark:bg-[#e0655e] dark:hover:bg-[#f09690]">Publish changes</button>
        </div>
    </div>
</section>
@endsection
