@extends('layouts.superadmin')

@section('title', 'CashPilot — CMS')

@section('content')
<section id="sec-cms-hero">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Hero Section</h1>
            <p class="text-[13.2px] text-inksoft">The first thing visitors see on the CashPilot landing page.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>Preview page</button>
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff]">Publish changes</button>
        </div>
    </div>
    <div class="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-[1.4fr_1fr]">
        <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
            <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
                <div><h3 class="text-[14.5px] font-semibold">Content</h3><div class="mt-0.5 text-xs text-inksoft">Headline, copy and call-to-action buttons</div></div>
            </div>
            <div class="grid grid-cols-1 gap-4 p-5 lg:grid-cols-2">
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Eyebrow tag <span class="text-[11.3px] font-normal text-inksoft">(small text above the headline)</span></label><input type="text" value="Trusted by 48,000+ people" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Headline</label><input type="text" value="Take control of your money, effortlessly" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Subheadline</label><textarea class="min-h-[90px] w-full resize-y rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]">Track spending, set budgets, and grow your savings — all in one simple app built for real life.</textarea></div>
                <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Primary button text</label><input type="text" value="Get started free" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Primary button link</label><input type="text" value="/signup" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Secondary button text</label><input type="text" value="Watch demo" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Secondary button link</label><input type="text" value="/demo" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            </div>
            <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
                <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
                <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff]">Save changes</button>
            </div>
        </div>
        <div class="rounded-[10px] border border-line bg-panel p-5 dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
            <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
                <div><h3 class="text-[14.5px] font-semibold">Hero image</h3><div class="mt-0.5 text-xs text-inksoft">Recommended size 1200×900px, JPG or PNG</div></div>
            </div>
            <div class="rounded-[10px] border-[1.5px] border-dashed border-line px-5 py-10 text-center text-inksoft dark:border-[#2a2c3d]">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" class="mx-auto size-[30px]"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>
                <div class="mt-3 font-semibold text-ink dark:text-[#ededf5]">hero-banner.jpg</div>
                <div class="mt-0.5 text-xs">1200×900 · 340 KB</div>
                <div class="mt-4"><button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[11px] py-1.5 text-[12.4px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Replace image</button></div>
            </div>
        </div>
    </div>
</section>

<section id="sec-cms-features">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Features Section</h1>
            <p class="text-[13.2px] text-inksoft">Highlight CashPilot&#39;s key features on the landing page.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Add feature</button>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Order</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Icon</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Title</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Description</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]"></th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle">1</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-lg">💰</td><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Smart budgeting</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Set monthly budgets and get alerts before you overspend.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" title="Edit" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" title="Delete" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle">2</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-lg">📊</td><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Advanced reports</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Visualize where your money goes with clear, simple charts.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle">3</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-lg">🔄</td><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Bank sync</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Connect your accounts and see transactions update automatically.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle">4</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-lg">🔒</td><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Bank-level security</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Your data is encrypted end-to-end and never sold.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-muted px-2.5 py-1 text-[11.6px] font-bold text-[#6b7089] dark:bg-[#242639] dark:text-[#b3b6cc]">Hidden</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

<section id="sec-cms-testimonials">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Testimonials</h1>
            <p class="text-[13.2px] text-inksoft">Customer quotes shown in the social proof section.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Add testimonial</button>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Customer</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Quote</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Rating</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]"></th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex items-center gap-2.5"><div class="flex size-[30px] flex-none items-center justify-center rounded-full bg-[#6e62f2] text-[11px] font-bold text-white">MR</div><div><div class="font-semibold text-ink dark:text-[#ededf5]">Mahin Rahman</div><div class="mt-px text-[11.8px] text-inksoft">Pro plan user</div></div></div></td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">&#34;CashPilot finally made budgeting feel simple instead of stressful.&#34;</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">⭐️⭐️⭐️⭐️⭐️</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" title="Edit" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" title="Delete" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex items-center gap-2.5"><div class="flex size-[30px] flex-none items-center justify-center rounded-full bg-[#e9a23b] text-[11px] font-bold text-white">FA</div><div><div class="font-semibold text-ink dark:text-[#ededf5]">Farzana Akter</div><div class="mt-px text-[11.8px] text-inksoft">Business plan user</div></div></div></td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">&#34;Bank sync alone saved our team hours every month.&#34;</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">⭐️⭐️⭐️⭐️⭐️</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex items-center gap-2.5"><div class="flex size-[30px] flex-none items-center justify-center rounded-full bg-[#1aa97a] text-[11px] font-bold text-white">NS</div><div><div class="font-semibold text-ink dark:text-[#ededf5]">Nusrat Sultana</div><div class="mt-px text-[11.8px] text-inksoft">Pro plan user</div></div></div></td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">&#34;The reports finally show me where all my money actually goes.&#34;</td><td class="whitespace-nowrap px-5 py-[13px] align-middle">⭐️⭐️⭐️⭐️</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-muted px-2.5 py-1 text-[11.6px] font-bold text-[#6b7089] dark:bg-[#242639] dark:text-[#b3b6cc]">Hidden</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                </tbody>
            </table>
        </div>
        <div class="flex items-center justify-between px-5 py-3.5 text-[12.3px] text-inksoft">
            <span>Showing 1–3 of 8 testimonials</span>
            <div class="flex gap-1.5"><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">‹</button><button type="button" class="size-7 rounded-[7px] border border-brand bg-brand text-xs font-bold text-white dark:border-[#7c72ff] dark:bg-[#7c72ff]">1</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">2</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">3</button><button type="button" class="size-7 rounded-[7px] border border-line bg-panel text-xs text-inksoft dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">›</button></div>
        </div>
    </div>
</section>
<section id="sec-cms-pricing">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Pricing Section</h1>
            <p class="text-[13.2px] text-inksoft">Control how subscription plans are displayed on the landing page.</p>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Show pricing section</div><div class="mt-0.5 text-xs text-inksoft">Display plan cards on the public landing page</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#7c72ff]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Show &#34;Most popular&#34; badge</div><div class="mt-0.5 text-xs text-inksoft">Highlight the Pro plan as most popular</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#7c72ff]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
        <div class="flex items-center justify-between border-b border-line px-5 py-4 last:border-b-0 dark:border-[#2a2c3d]"><div><div class="text-[13.4px] font-semibold">Show yearly discount toggle</div><div class="mt-0.5 text-xs text-inksoft">Let visitors switch between monthly and yearly pricing</div></div><button type="button" data-switch data-on="true" class="group h-[22px] w-[38px] flex-none rounded-full bg-muted transition-colors data-[on=true]:bg-brand dark:bg-[#242639] dark:data-[on=true]:bg-[#7c72ff]"><span class="mt-[2px] block size-[18px] translate-x-[2px] rounded-full bg-white shadow transition-transform group-data-[on=true]:translate-x-[18px]"></span></button></div>
    </div>
    <div class="mt-6 rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div><h3 class="text-[14.5px] font-semibold">Section copy</h3><div class="mt-0.5 text-xs text-inksoft">Headline and subtext shown above the plan cards</div></div>
        </div>
        <div class="grid grid-cols-1 gap-4 p-5 lg:grid-cols-2">
            <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Section headline</label><input type="text" value="Simple pricing, no surprises" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Section subtext</label><textarea class="min-h-[90px] w-full resize-y rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]">Start free, upgrade anytime. Cancel whenever you want.</textarea></div>
        </div>
        <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff]">Save changes</button>
        </div>
    </div>
</section>

<section id="sec-cms-faq">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">FAQ</h1>
            <p class="text-[13.2px] text-inksoft">Frequently asked questions shown near the bottom of the landing page.</p>
        </div>
        <div class="flex gap-2.5">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff] [&>svg]:size-[14px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>Add question</button>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="overflow-x-auto">
            <table class="w-full border-collapse text-[13.2px]">
                <thead><tr><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Question</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Answer</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]">Status</th><th class="whitespace-nowrap border-b border-line px-5 py-[11px] text-left text-[11.3px] font-bold tracking-wide text-[#9497ab] dark:border-[#2a2c3d] dark:text-[#8d90ac]"></th></tr></thead>
                <tbody>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Is there a free plan?</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Yes — the Free plan gives you 2 accounts and basic expense tracking, no card required.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" title="Edit" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" title="Delete" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Can I cancel anytime?</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Yes, you can cancel your subscription at any time from your account settings.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Is my financial data secure?</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">All data is encrypted in transit and at rest, and is never sold to third parties.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-goodtint px-2.5 py-1 text-[11.6px] font-bold text-good dark:bg-[#123b2c] dark:text-[#3ed9a0]">Visible</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                    <tr class="border-b border-line last:border-b-0 hover:bg-[#fbfbfd] dark:border-[#2a2c3d] dark:hover:bg-[#242639]"><td class="whitespace-nowrap px-5 py-[13px] align-middle font-semibold text-ink dark:text-[#ededf5]">Do you offer refunds?</td><td class="whitespace-nowrap px-5 py-[13px] align-middle text-[11.8px] text-inksoft">Reach out within 14 days of purchase and our team will review your request.</td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><span class="inline-flex items-center gap-[5px] rounded-full bg-muted px-2.5 py-1 text-[11.6px] font-bold text-[#6b7089] dark:bg-[#242639] dark:text-[#b3b6cc]">Hidden</span></td><td class="whitespace-nowrap px-5 py-[13px] align-middle"><div class="flex gap-1.5"><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.12 2.12 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button type="button" class="flex size-7 items-center justify-center rounded-[7px] text-[#8b8fa3] hover:bg-muted hover:text-ink dark:text-[#9497b8] dark:hover:bg-[#242639] dark:hover:text-[#ededf5] [&>svg]:size-[14.5px]"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>
                </tbody>
            </table>
        </div>
    </div>
</section>

<section id="sec-cms-footer">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">Footer</h1>
            <p class="text-[13.2px] text-inksoft">Company info, links and social channels shown in the site footer.</p>
        </div>
    </div>
    <div class="mb-6 grid grid-cols-1 gap-6 lg:grid-cols-2">
        <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
            <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
                <div><h3 class="text-[14.5px] font-semibold">Company info</h3><div class="mt-0.5 text-xs text-inksoft">Shown in the footer column</div></div>
            </div>
            <div class="grid grid-cols-1 gap-4 p-5 lg:grid-cols-2">
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Short description</label><textarea class="min-h-[90px] w-full resize-y rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]">CashPilot helps you track income and expenses, manage budgets, and take control of your money.</textarea></div>
                <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Contact email</label><input type="email" value="hello@cashpilot.app" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Contact phone</label><input type="text" value="+880 1XXX-XXXXXX" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Office address</label><input type="text" value="Gulshan Avenue, Dhaka 1212, Bangladesh" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Copyright text</label><input type="text" value="© 2026 CashPilot. All rights reserved." class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            </div>
            <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
                <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
                <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff]">Save changes</button>
            </div>
        </div>
        <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
            <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
                <div><h3 class="text-[14.5px] font-semibold">Social links</h3><div class="mt-0.5 text-xs text-inksoft">Icons shown in the footer</div></div>
            </div>
            <div class="grid grid-cols-1 gap-4 p-5 lg:grid-cols-2">
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Facebook</label><input type="text" value="https://facebook.com/cashpilot" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Instagram</label><input type="text" value="https://instagram.com/cashpilot" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">X (Twitter)</label><input type="text" value="https://x.com/cashpilot" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
                <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">LinkedIn</label><input type="text" value="https://linkedin.com/company/cashpilot" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            </div>
            <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
                <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
                <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff]">Save changes</button>
            </div>
        </div>
    </div>
</section>

<section id="sec-cms-seo">
    <div class="mb-6 flex flex-wrap items-end justify-between gap-3">
        <div>
            <h1 class="mb-1 text-xl font-bold tracking-tight">SEO &amp; Meta</h1>
            <p class="text-[13.2px] text-inksoft">How the landing page appears in search engines and link previews.</p>
        </div>
    </div>
    <div class="rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div><h3 class="text-[14.5px] font-semibold">Meta tags</h3><div class="mt-0.5 text-xs text-inksoft">Used by search engines and social platforms</div></div>
        </div>
        <div class="grid grid-cols-1 gap-4 p-5 lg:grid-cols-2">
            <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Meta title <span class="text-[11.3px] font-normal text-inksoft">(max 60 characters)</span></label><input type="text" value="CashPilot — Budgeting &amp; Expense Tracking App" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Meta description <span class="text-[11.3px] font-normal text-inksoft">(max 160 characters)</span></label><textarea class="min-h-[90px] w-full resize-y rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]">Track spending, set budgets, and grow your savings with CashPilot — the simple money app trusted by 48,000+ people.</textarea></div>
            <div class="flex flex-col gap-1.5 lg:col-span-2"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Focus keywords</label><input type="text" value="budgeting app, expense tracker, personal finance" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Google Analytics ID</label><input type="text" value="G-XXXXXXXXXX" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
            <div class="flex flex-col gap-1.5"><label class="text-[12.6px] font-semibold text-[#3e4159] dark:text-[#d6d8e8]">Search Console verification</label><input type="text" value="verified ✅" class="w-full rounded-lg border border-line bg-panel px-3 py-2.5 text-[13px] text-ink outline-none focus:border-brand dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5]"></div>
        </div>
        <div class="flex justify-end gap-2.5 border-t border-line px-5 py-4 dark:border-[#2a2c3d]">
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[15px] py-2 text-[13.3px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Discard</button>
            <button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-brand bg-brand px-[15px] py-2 text-[13.3px] font-semibold text-white hover:bg-branddark dark:border-[#7c72ff] dark:bg-[#7c72ff] dark:hover:bg-[#9089ff]">Save changes</button>
        </div>
    </div>
    <div class="mt-6 rounded-[10px] border border-line bg-panel dark:border-[#2a2c3d] dark:bg-[#1b1d2a]">
        <div class="flex items-center justify-between border-b border-line px-5 py-4 dark:border-[#2a2c3d]">
            <div><h3 class="text-[14.5px] font-semibold">Social preview image</h3><div class="mt-0.5 text-xs text-inksoft">Shown when the link is shared on social media (1200×630px)</div></div>
        </div>
        <div class="px-5 pb-5">
            <div class="rounded-[10px] border-[1.5px] border-dashed border-line px-5 py-10 text-center text-inksoft dark:border-[#2a2c3d]">
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" class="mx-auto size-[30px]"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>
                <div class="mt-3 font-semibold text-ink dark:text-[#ededf5]">og-image.jpg</div>
                <div class="mt-0.5 text-xs">1200×630 · 210 KB</div>
                <div class="mt-4"><button type="button" class="inline-flex items-center gap-[7px] whitespace-nowrap rounded-lg border border-line bg-panel px-[11px] py-1.5 text-[12.4px] font-semibold text-ink hover:bg-muted dark:border-[#2a2c3d] dark:bg-[#1b1d2a] dark:text-[#ededf5] dark:hover:bg-[#242639]">Replace image</button></div>
            </div>
        </div>
    </div>
</section>
@endsection
